# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alibabacloud/v1beta1/scope_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from k8s.io.apimachinery.pkg.apis.meta.v1 import generated_pb2 as k8s_dot_io_dot_apimachinery_dot_pkg_dot_apis_dot_meta_dot_v1_dot_generated__pb2
from k8s.io.apimachinery.pkg.util.intstr import generated_pb2 as k8s_dot_io_dot_apimachinery_dot_pkg_dot_util_dot_intstr_dot_generated__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='alibabacloud/v1beta1/scope_config.proto',
  package='istio.alibabacloud.v1beta1',
  syntax='proto3',
  serialized_options=b'Z!istio.io/api/alibabacloud/v1beta1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'alibabacloud/v1beta1/scope_config.proto\x12\x1aistio.alibabacloud.v1beta1\x1a\x34k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto\x1a\x33k8s.io/apimachinery/pkg/util/intstr/generated.proto\"\xd7\x02\n\x0bScopeConfig\x12\x43\n\x05scope\x18\x01 \x01(\x0b\x32-.istio.alibabacloud.v1beta1.ScopeConfig.ScopeR\x05scope\x1aK\n\rRollingUpdate\x12\x1a\n\x08\x62\x61tchNum\x18\x01 \x01(\rR\x08\x62\x61tchNum\x12\x1e\n\nbatchOrder\x18\x02 \x01(\rR\nbatchOrder\x1a\xb5\x01\n\x05Scope\x12O\n\x08selector\x18\x01 \x01(\x0b\x32\x33.k8s.io.apimachinery.pkg.apis.meta.v1.LabelSelectorR\x08selector\x12[\n\rrollingUpdate\x18\x02 \x01(\x0b\x32\x35.istio.alibabacloud.v1beta1.ScopeConfig.RollingUpdateR\rrollingUpdateB#Z!istio.io/api/alibabacloud/v1beta1b\x06proto3'
  ,
  dependencies=[k8s_dot_io_dot_apimachinery_dot_pkg_dot_apis_dot_meta_dot_v1_dot_generated__pb2.DESCRIPTOR,k8s_dot_io_dot_apimachinery_dot_pkg_dot_util_dot_intstr_dot_generated__pb2.DESCRIPTOR,])




_SCOPECONFIG_ROLLINGUPDATE = _descriptor.Descriptor(
  name='RollingUpdate',
  full_name='istio.alibabacloud.v1beta1.ScopeConfig.RollingUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='batchNum', full_name='istio.alibabacloud.v1beta1.ScopeConfig.RollingUpdate.batchNum', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='batchNum', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batchOrder', full_name='istio.alibabacloud.v1beta1.ScopeConfig.RollingUpdate.batchOrder', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='batchOrder', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=338,
)

_SCOPECONFIG_SCOPE = _descriptor.Descriptor(
  name='Scope',
  full_name='istio.alibabacloud.v1beta1.ScopeConfig.Scope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='selector', full_name='istio.alibabacloud.v1beta1.ScopeConfig.Scope.selector', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='selector', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rollingUpdate', full_name='istio.alibabacloud.v1beta1.ScopeConfig.Scope.rollingUpdate', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='rollingUpdate', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=522,
)

_SCOPECONFIG = _descriptor.Descriptor(
  name='ScopeConfig',
  full_name='istio.alibabacloud.v1beta1.ScopeConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='scope', full_name='istio.alibabacloud.v1beta1.ScopeConfig.scope', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='scope', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SCOPECONFIG_ROLLINGUPDATE, _SCOPECONFIG_SCOPE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=522,
)

_SCOPECONFIG_ROLLINGUPDATE.containing_type = _SCOPECONFIG
_SCOPECONFIG_SCOPE.fields_by_name['selector'].message_type = k8s_dot_io_dot_apimachinery_dot_pkg_dot_apis_dot_meta_dot_v1_dot_generated__pb2._LABELSELECTOR
_SCOPECONFIG_SCOPE.fields_by_name['rollingUpdate'].message_type = _SCOPECONFIG_ROLLINGUPDATE
_SCOPECONFIG_SCOPE.containing_type = _SCOPECONFIG
_SCOPECONFIG.fields_by_name['scope'].message_type = _SCOPECONFIG_SCOPE
DESCRIPTOR.message_types_by_name['ScopeConfig'] = _SCOPECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScopeConfig = _reflection.GeneratedProtocolMessageType('ScopeConfig', (_message.Message,), {

  'RollingUpdate' : _reflection.GeneratedProtocolMessageType('RollingUpdate', (_message.Message,), {
    'DESCRIPTOR' : _SCOPECONFIG_ROLLINGUPDATE,
    '__module__' : 'alibabacloud.v1beta1.scope_config_pb2'
    # @@protoc_insertion_point(class_scope:istio.alibabacloud.v1beta1.ScopeConfig.RollingUpdate)
    })
  ,

  'Scope' : _reflection.GeneratedProtocolMessageType('Scope', (_message.Message,), {
    'DESCRIPTOR' : _SCOPECONFIG_SCOPE,
    '__module__' : 'alibabacloud.v1beta1.scope_config_pb2'
    # @@protoc_insertion_point(class_scope:istio.alibabacloud.v1beta1.ScopeConfig.Scope)
    })
  ,
  'DESCRIPTOR' : _SCOPECONFIG,
  '__module__' : 'alibabacloud.v1beta1.scope_config_pb2'
  # @@protoc_insertion_point(class_scope:istio.alibabacloud.v1beta1.ScopeConfig)
  })
_sym_db.RegisterMessage(ScopeConfig)
_sym_db.RegisterMessage(ScopeConfig.RollingUpdate)
_sym_db.RegisterMessage(ScopeConfig.Scope)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
