# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alibabacloud/v1beta1/traffic_label.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from networking.v1alpha3 import virtual_service_pb2 as networking_dot_v1alpha3_dot_virtual__service__pb2
from networking.v1alpha3 import sidecar_pb2 as networking_dot_v1alpha3_dot_sidecar__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='alibabacloud/v1beta1/traffic_label.proto',
  package='istio.alibabacloud.v1beta1',
  syntax='proto3',
  serialized_options=b'Z!istio.io/api/alibabacloud/v1beta1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n(alibabacloud/v1beta1/traffic_label.proto\x12\x1aistio.alibabacloud.v1beta1\x1a)networking/v1alpha3/virtual_service.proto\x1a!networking/v1alpha3/sidecar.proto\"\xc2\x01\n\x0cTrafficLabel\x12X\n\x11workload_selector\x18\x01 \x01(\x0b\x32+.istio.networking.v1alpha3.WorkloadSelectorR\x10workloadSelector\x12\x42\n\x05rules\x18\x02 \x03(\x0b\x32,.istio.alibabacloud.v1beta1.TrafficLabelRuleR\x05rules\x12\x14\n\x05hosts\x18\x05 \x03(\tR\x05hosts\"\xc9\x01\n\x10TrafficLabelRule\x12<\n\x06labels\x18\x02 \x03(\x0b\x32$.istio.alibabacloud.v1beta1.LabelVarR\x06labels\x12\x1a\n\x08\x61ttachTo\x18\x03 \x03(\tR\x08\x61ttachTo\x12\x1c\n\tprotocols\x18\x04 \x01(\tR\tprotocols\x12=\n\x04http\x18\x0b \x03(\x0b\x32).istio.alibabacloud.v1beta1.HTTPLabelRuleR\x04http\"Z\n\x08LabelVar\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n\tvalueFrom\x18\x02 \x03(\tR\tvalueFrom\x12\x1c\n\toverwrite\x18\x05 \x01(\x08R\toverwrite\"\xac\x01\n\rHTTPLabelRule\x12\x41\n\x05match\x18\x01 \x03(\x0b\x32+.istio.networking.v1alpha3.HTTPMatchRequestR\x05match\x12<\n\x06labels\x18\x05 \x03(\x0b\x32$.istio.alibabacloud.v1beta1.LabelVarR\x06labels\x12\x1a\n\x08\x61ttachTo\x18\x06 \x03(\tR\x08\x61ttachToB#Z!istio.io/api/alibabacloud/v1beta1b\x06proto3'
  ,
  dependencies=[networking_dot_v1alpha3_dot_virtual__service__pb2.DESCRIPTOR,networking_dot_v1alpha3_dot_sidecar__pb2.DESCRIPTOR,])




_TRAFFICLABEL = _descriptor.Descriptor(
  name='TrafficLabel',
  full_name='istio.alibabacloud.v1beta1.TrafficLabel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workload_selector', full_name='istio.alibabacloud.v1beta1.TrafficLabel.workload_selector', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='workloadSelector', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rules', full_name='istio.alibabacloud.v1beta1.TrafficLabel.rules', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='rules', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hosts', full_name='istio.alibabacloud.v1beta1.TrafficLabel.hosts', index=2,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='hosts', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=345,
)


_TRAFFICLABELRULE = _descriptor.Descriptor(
  name='TrafficLabelRule',
  full_name='istio.alibabacloud.v1beta1.TrafficLabelRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='labels', full_name='istio.alibabacloud.v1beta1.TrafficLabelRule.labels', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='labels', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attachTo', full_name='istio.alibabacloud.v1beta1.TrafficLabelRule.attachTo', index=1,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='attachTo', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='protocols', full_name='istio.alibabacloud.v1beta1.TrafficLabelRule.protocols', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='protocols', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='http', full_name='istio.alibabacloud.v1beta1.TrafficLabelRule.http', index=3,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='http', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=549,
)


_LABELVAR = _descriptor.Descriptor(
  name='LabelVar',
  full_name='istio.alibabacloud.v1beta1.LabelVar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='istio.alibabacloud.v1beta1.LabelVar.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='name', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valueFrom', full_name='istio.alibabacloud.v1beta1.LabelVar.valueFrom', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='valueFrom', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='overwrite', full_name='istio.alibabacloud.v1beta1.LabelVar.overwrite', index=2,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='overwrite', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=551,
  serialized_end=641,
)


_HTTPLABELRULE = _descriptor.Descriptor(
  name='HTTPLabelRule',
  full_name='istio.alibabacloud.v1beta1.HTTPLabelRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='match', full_name='istio.alibabacloud.v1beta1.HTTPLabelRule.match', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='match', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='labels', full_name='istio.alibabacloud.v1beta1.HTTPLabelRule.labels', index=1,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='labels', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attachTo', full_name='istio.alibabacloud.v1beta1.HTTPLabelRule.attachTo', index=2,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='attachTo', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=644,
  serialized_end=816,
)

_TRAFFICLABEL.fields_by_name['workload_selector'].message_type = networking_dot_v1alpha3_dot_sidecar__pb2._WORKLOADSELECTOR
_TRAFFICLABEL.fields_by_name['rules'].message_type = _TRAFFICLABELRULE
_TRAFFICLABELRULE.fields_by_name['labels'].message_type = _LABELVAR
_TRAFFICLABELRULE.fields_by_name['http'].message_type = _HTTPLABELRULE
_HTTPLABELRULE.fields_by_name['match'].message_type = networking_dot_v1alpha3_dot_virtual__service__pb2._HTTPMATCHREQUEST
_HTTPLABELRULE.fields_by_name['labels'].message_type = _LABELVAR
DESCRIPTOR.message_types_by_name['TrafficLabel'] = _TRAFFICLABEL
DESCRIPTOR.message_types_by_name['TrafficLabelRule'] = _TRAFFICLABELRULE
DESCRIPTOR.message_types_by_name['LabelVar'] = _LABELVAR
DESCRIPTOR.message_types_by_name['HTTPLabelRule'] = _HTTPLABELRULE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrafficLabel = _reflection.GeneratedProtocolMessageType('TrafficLabel', (_message.Message,), {
  'DESCRIPTOR' : _TRAFFICLABEL,
  '__module__' : 'alibabacloud.v1beta1.traffic_label_pb2'
  # @@protoc_insertion_point(class_scope:istio.alibabacloud.v1beta1.TrafficLabel)
  })
_sym_db.RegisterMessage(TrafficLabel)

TrafficLabelRule = _reflection.GeneratedProtocolMessageType('TrafficLabelRule', (_message.Message,), {
  'DESCRIPTOR' : _TRAFFICLABELRULE,
  '__module__' : 'alibabacloud.v1beta1.traffic_label_pb2'
  # @@protoc_insertion_point(class_scope:istio.alibabacloud.v1beta1.TrafficLabelRule)
  })
_sym_db.RegisterMessage(TrafficLabelRule)

LabelVar = _reflection.GeneratedProtocolMessageType('LabelVar', (_message.Message,), {
  'DESCRIPTOR' : _LABELVAR,
  '__module__' : 'alibabacloud.v1beta1.traffic_label_pb2'
  # @@protoc_insertion_point(class_scope:istio.alibabacloud.v1beta1.LabelVar)
  })
_sym_db.RegisterMessage(LabelVar)

HTTPLabelRule = _reflection.GeneratedProtocolMessageType('HTTPLabelRule', (_message.Message,), {
  'DESCRIPTOR' : _HTTPLABELRULE,
  '__module__' : 'alibabacloud.v1beta1.traffic_label_pb2'
  # @@protoc_insertion_point(class_scope:istio.alibabacloud.v1beta1.HTTPLabelRule)
  })
_sym_db.RegisterMessage(HTTPLabelRule)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
