//go:build !ignore_autogenerated

// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ASMProxyConfig) DeepCopyInto(out *ASMProxyConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ASMProxyConfig.
func (in *ASMProxyConfig) DeepCopy() *ASMProxyConfig {
	if in == nil {
		return nil
	}
	out := new(ASMProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ASMProxyConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ASMProxyConfigList) DeepCopyInto(out *ASMProxyConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ASMProxyConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ASMProxyConfigList.
func (in *ASMProxyConfigList) DeepCopy() *ASMProxyConfigList {
	if in == nil {
		return nil
	}
	out := new(ASMProxyConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ASMProxyConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ASMProxyConfigSpec) DeepCopyInto(out *ASMProxyConfigSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = (*in).DeepCopy()
	}
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(Int32)
		**out = **in
	}
	if in.TerminationDrainDuration != nil {
		in, out := &in.TerminationDrainDuration, &out.TerminationDrainDuration
		*out = new(string)
		**out = **in
	}
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = new(v1.Lifecycle)
		(*in).DeepCopyInto(*out)
	}
	if in.SidecarProxyInitResource != nil {
		in, out := &in.SidecarProxyInitResource, &out.SidecarProxyInitResource
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.SidecarProxyResource != nil {
		in, out := &in.SidecarProxyResource, &out.SidecarProxyResource
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.ScaledSidecarResource != nil {
		in, out := &in.ScaledSidecarResource, &out.ScaledSidecarResource
		*out = new(ScaledSidecarResource)
		**out = **in
	}
	if in.ExcludeOutboundPorts != nil {
		in, out := &in.ExcludeOutboundPorts, &out.ExcludeOutboundPorts
		*out = new(string)
		**out = **in
	}
	if in.ExcludeOutboundIPRanges != nil {
		in, out := &in.ExcludeOutboundIPRanges, &out.ExcludeOutboundIPRanges
		*out = new(string)
		**out = **in
	}
	if in.IncludeOutboundIPRanges != nil {
		in, out := &in.IncludeOutboundIPRanges, &out.IncludeOutboundIPRanges
		*out = new(string)
		**out = **in
	}
	if in.ExcludeInboundPorts != nil {
		in, out := &in.ExcludeInboundPorts, &out.ExcludeInboundPorts
		*out = new(string)
		**out = **in
	}
	if in.IncludeInboundPorts != nil {
		in, out := &in.IncludeInboundPorts, &out.IncludeInboundPorts
		*out = new(string)
		**out = **in
	}
	if in.IncludeOutboundPorts != nil {
		in, out := &in.IncludeOutboundPorts, &out.IncludeOutboundPorts
		*out = new(string)
		**out = **in
	}
	if in.IstioDNSProxyEnabled != nil {
		in, out := &in.IstioDNSProxyEnabled, &out.IstioDNSProxyEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ProxyStatsMatcher != nil {
		in, out := &in.ProxyStatsMatcher, &out.ProxyStatsMatcher
		*out = new(ProxyStatsMatcher)
		(*in).DeepCopyInto(*out)
	}
	if in.HoldApplicationUntilProxyStarts != nil {
		in, out := &in.HoldApplicationUntilProxyStarts, &out.HoldApplicationUntilProxyStarts
		*out = new(bool)
		**out = **in
	}
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(string)
		**out = **in
	}
	if in.Tracing != nil {
		in, out := &in.Tracing, &out.Tracing
		*out = new(ProxyTracingConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.InterceptionMode != nil {
		in, out := &in.InterceptionMode, &out.InterceptionMode
		*out = new(string)
		**out = **in
	}
	if in.DrainDuration != nil {
		in, out := &in.DrainDuration, &out.DrainDuration
		*out = new(string)
		**out = **in
	}
	if in.ParentShutdownDuration != nil {
		in, out := &in.ParentShutdownDuration, &out.ParentShutdownDuration
		*out = new(string)
		**out = **in
	}
	if in.ProxyMetadata != nil {
		in, out := &in.ProxyMetadata, &out.ProxyMetadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExtraStatTags != nil {
		in, out := &in.ExtraStatTags, &out.ExtraStatTags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PrivateKeyProvider != nil {
		in, out := &in.PrivateKeyProvider, &out.PrivateKeyProvider
		*out = new(PrivateKeyProviderConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Privileged != nil {
		in, out := &in.Privileged, &out.Privileged
		*out = new(bool)
		**out = **in
	}
	if in.EnableCoreDump != nil {
		in, out := &in.EnableCoreDump, &out.EnableCoreDump
		*out = new(bool)
		**out = **in
	}
	if in.ReadinessInitialDelaySeconds != nil {
		in, out := &in.ReadinessInitialDelaySeconds, &out.ReadinessInitialDelaySeconds
		*out = new(int32)
		**out = **in
	}
	if in.ReadinessPeriodSeconds != nil {
		in, out := &in.ReadinessPeriodSeconds, &out.ReadinessPeriodSeconds
		*out = new(int32)
		**out = **in
	}
	if in.ReadinessFailureThreshold != nil {
		in, out := &in.ReadinessFailureThreshold, &out.ReadinessFailureThreshold
		*out = new(int32)
		**out = **in
	}
	if in.SidecarProxyInitAckSloResource != nil {
		in, out := &in.SidecarProxyInitAckSloResource, &out.SidecarProxyInitAckSloResource
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.SidecarProxyAckSloResource != nil {
		in, out := &in.SidecarProxyAckSloResource, &out.SidecarProxyAckSloResource
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.SMC != nil {
		in, out := &in.SMC, &out.SMC
		*out = new(SMCConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.RuntimeValues != nil {
		in, out := &in.RuntimeValues, &out.RuntimeValues
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ASMProxyConfigSpec.
func (in *ASMProxyConfigSpec) DeepCopy() *ASMProxyConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ASMProxyConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ASMProxyConfigStatus) DeepCopyInto(out *ASMProxyConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ASMProxyConfigStatus.
func (in *ASMProxyConfigStatus) DeepCopy() *ASMProxyConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ASMProxyConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CryptoMbConfiguration) DeepCopyInto(out *CryptoMbConfiguration) {
	*out = *in
	if in.PollDelay != nil {
		in, out := &in.PollDelay, &out.PollDelay
		*out = new(string)
		**out = **in
	}
	if in.Fallback != nil {
		in, out := &in.Fallback, &out.Fallback
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CryptoMbConfiguration.
func (in *CryptoMbConfiguration) DeepCopy() *CryptoMbConfiguration {
	if in == nil {
		return nil
	}
	out := new(CryptoMbConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Int32) DeepCopyInto(out *Int32) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Int32.
func (in *Int32) DeepCopy() *Int32 {
	if in == nil {
		return nil
	}
	out := new(Int32)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateKeyProviderConfiguration) DeepCopyInto(out *PrivateKeyProviderConfiguration) {
	*out = *in
	if in.CryptoMb != nil {
		in, out := &in.CryptoMb, &out.CryptoMb
		*out = new(CryptoMbConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateKeyProviderConfiguration.
func (in *PrivateKeyProviderConfiguration) DeepCopy() *PrivateKeyProviderConfiguration {
	if in == nil {
		return nil
	}
	out := new(PrivateKeyProviderConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyImage) DeepCopyInto(out *ProxyImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyImage.
func (in *ProxyImage) DeepCopy() *ProxyImage {
	if in == nil {
		return nil
	}
	out := new(ProxyImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyStatsMatcher) DeepCopyInto(out *ProxyStatsMatcher) {
	*out = *in
	if in.InclusionPrefixes != nil {
		in, out := &in.InclusionPrefixes, &out.InclusionPrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InclusionSuffixes != nil {
		in, out := &in.InclusionSuffixes, &out.InclusionSuffixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InclusionRegexps != nil {
		in, out := &in.InclusionRegexps, &out.InclusionRegexps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyStatsMatcher.
func (in *ProxyStatsMatcher) DeepCopy() *ProxyStatsMatcher {
	if in == nil {
		return nil
	}
	out := new(ProxyStatsMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyTracingConfiguration) DeepCopyInto(out *ProxyTracingConfiguration) {
	*out = *in
	if in.Sampling != nil {
		in, out := &in.Sampling, &out.Sampling
		*out = new(float32)
		**out = **in
	}
	if in.CustomTags != nil {
		in, out := &in.CustomTags, &out.CustomTags
		*out = make(map[string]ProxyTracingCustomTag, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.MaxPathTagLength != nil {
		in, out := &in.MaxPathTagLength, &out.MaxPathTagLength
		*out = new(uint32)
		**out = **in
	}
	if in.Zipkin != nil {
		in, out := &in.Zipkin, &out.Zipkin
		*out = new(ProxyTracingZipkin)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyTracingConfiguration.
func (in *ProxyTracingConfiguration) DeepCopy() *ProxyTracingConfiguration {
	if in == nil {
		return nil
	}
	out := new(ProxyTracingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyTracingCustomTag) DeepCopyInto(out *ProxyTracingCustomTag) {
	*out = *in
	if in.Literal != nil {
		in, out := &in.Literal, &out.Literal
		*out = new(ProxyTracingCustomTag_Literal)
		(*in).DeepCopyInto(*out)
	}
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(ProxyTracingCustomTag_Named)
		(*in).DeepCopyInto(*out)
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = new(ProxyTracingCustomTag_Named)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyTracingCustomTag.
func (in *ProxyTracingCustomTag) DeepCopy() *ProxyTracingCustomTag {
	if in == nil {
		return nil
	}
	out := new(ProxyTracingCustomTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyTracingCustomTag_Literal) DeepCopyInto(out *ProxyTracingCustomTag_Literal) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyTracingCustomTag_Literal.
func (in *ProxyTracingCustomTag_Literal) DeepCopy() *ProxyTracingCustomTag_Literal {
	if in == nil {
		return nil
	}
	out := new(ProxyTracingCustomTag_Literal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyTracingCustomTag_Named) DeepCopyInto(out *ProxyTracingCustomTag_Named) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.DefaultValue != nil {
		in, out := &in.DefaultValue, &out.DefaultValue
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyTracingCustomTag_Named.
func (in *ProxyTracingCustomTag_Named) DeepCopy() *ProxyTracingCustomTag_Named {
	if in == nil {
		return nil
	}
	out := new(ProxyTracingCustomTag_Named)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyTracingZipkin) DeepCopyInto(out *ProxyTracingZipkin) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyTracingZipkin.
func (in *ProxyTracingZipkin) DeepCopy() *ProxyTracingZipkin {
	if in == nil {
		return nil
	}
	out := new(ProxyTracingZipkin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMCConfiguration) DeepCopyInto(out *SMCConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMCConfiguration.
func (in *SMCConfiguration) DeepCopy() *SMCConfiguration {
	if in == nil {
		return nil
	}
	out := new(SMCConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaledSidecarResource) DeepCopyInto(out *ScaledSidecarResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaledSidecarResource.
func (in *ScaledSidecarResource) DeepCopy() *ScaledSidecarResource {
	if in == nil {
		return nil
	}
	out := new(ScaledSidecarResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficLabel) DeepCopyInto(out *TrafficLabel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficLabel.
func (in *TrafficLabel) DeepCopy() *TrafficLabel {
	if in == nil {
		return nil
	}
	out := new(TrafficLabel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrafficLabel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficLabelList) DeepCopyInto(out *TrafficLabelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]*TrafficLabel, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TrafficLabel)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficLabelList.
func (in *TrafficLabelList) DeepCopy() *TrafficLabelList {
	if in == nil {
		return nil
	}
	out := new(TrafficLabelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrafficLabelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
