// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1beta1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using ScopeConfig within kubernetes types, where deepcopy-gen is used.
func (in *ScopeConfig) DeepCopyInto(out *ScopeConfig) {
	p := proto.Clone(in).(*ScopeConfig)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeConfig. Required by controller-gen.
func (in *ScopeConfig) DeepCopy() *ScopeConfig {
	if in == nil {
		return nil
	}
	out := new(ScopeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ScopeConfig. Required by controller-gen.
func (in *ScopeConfig) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ScopeConfig_RollingUpdate within kubernetes types, where deepcopy-gen is used.
func (in *ScopeConfig_RollingUpdate) DeepCopyInto(out *ScopeConfig_RollingUpdate) {
	p := proto.Clone(in).(*ScopeConfig_RollingUpdate)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeConfig_RollingUpdate. Required by controller-gen.
func (in *ScopeConfig_RollingUpdate) DeepCopy() *ScopeConfig_RollingUpdate {
	if in == nil {
		return nil
	}
	out := new(ScopeConfig_RollingUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ScopeConfig_RollingUpdate. Required by controller-gen.
func (in *ScopeConfig_RollingUpdate) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ScopeConfig_Scope within kubernetes types, where deepcopy-gen is used.
func (in *ScopeConfig_Scope) DeepCopyInto(out *ScopeConfig_Scope) {
	p := proto.Clone(in).(*ScopeConfig_Scope)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeConfig_Scope. Required by controller-gen.
func (in *ScopeConfig_Scope) DeepCopy() *ScopeConfig_Scope {
	if in == nil {
		return nil
	}
	out := new(ScopeConfig_Scope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ScopeConfig_Scope. Required by controller-gen.
func (in *ScopeConfig_Scope) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
