// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: alibabacloud/v1beta1/scope_config.proto

package v1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	_ "k8s.io/apimachinery/pkg/util/intstr"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration affecting traffic routing.
//
// <!-- crd generation tags
// +cue-gen:ScopeConfig:groupName:istio.alibabacloud.com
// +cue-gen:ScopeConfig:version:v1beta1
// +cue-gen:ScopeConfig:storageVersion
// +cue-gen:ScopeConfig:annotations:helm.sh/resource-policy=keep
// +cue-gen:ScopeConfig:labels:app=istio-pilot,chart=istio,heritage=Tiller,release=istio
// +cue-gen:ScopeConfig:subresource:status
// +cue-gen:ScopeConfig:scope:Namespaced
// +cue-gen:ScopeConfig:resource:categories=alibabacloud-com,istio-alibabacloud-com,shortNames=scp
// +cue-gen:ScopeConfig:printerColumn:name=Age,type=date,JSONPath=.metadata.creationTimestamp,description="CreationTimestamp is a timestamp
// representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations.
// Clients may not set this value. It is represented in RFC3339 form and is in UTC.
// Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata"
// +cue-gen:ScopeConfig:preserveUnknownFields:false
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=istio.alibabacloud.com/v1beta1
// +genclient
// +k8s:deepcopy-gen=true
// -->
type ScopeConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scope *ScopeConfig_Scope `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
}

func (x *ScopeConfig) Reset() {
	*x = ScopeConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alibabacloud_v1beta1_scope_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScopeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeConfig) ProtoMessage() {}

func (x *ScopeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_alibabacloud_v1beta1_scope_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeConfig.ProtoReflect.Descriptor instead.
func (*ScopeConfig) Descriptor() ([]byte, []int) {
	return file_alibabacloud_v1beta1_scope_config_proto_rawDescGZIP(), []int{0}
}

func (x *ScopeConfig) GetScope() *ScopeConfig_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type ScopeConfig_RollingUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BatchNum   uint32 `protobuf:"varint,1,opt,name=batchNum,proto3" json:"batchNum,omitempty"`
	BatchOrder uint32 `protobuf:"varint,2,opt,name=batchOrder,proto3" json:"batchOrder,omitempty"`
}

func (x *ScopeConfig_RollingUpdate) Reset() {
	*x = ScopeConfig_RollingUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alibabacloud_v1beta1_scope_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScopeConfig_RollingUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeConfig_RollingUpdate) ProtoMessage() {}

func (x *ScopeConfig_RollingUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_alibabacloud_v1beta1_scope_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeConfig_RollingUpdate.ProtoReflect.Descriptor instead.
func (*ScopeConfig_RollingUpdate) Descriptor() ([]byte, []int) {
	return file_alibabacloud_v1beta1_scope_config_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ScopeConfig_RollingUpdate) GetBatchNum() uint32 {
	if x != nil {
		return x.BatchNum
	}
	return 0
}

func (x *ScopeConfig_RollingUpdate) GetBatchOrder() uint32 {
	if x != nil {
		return x.BatchOrder
	}
	return 0
}

type ScopeConfig_Scope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Selector      *v1.LabelSelector          `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	RollingUpdate *ScopeConfig_RollingUpdate `protobuf:"bytes,2,opt,name=rollingUpdate,proto3" json:"rollingUpdate,omitempty"`
}

func (x *ScopeConfig_Scope) Reset() {
	*x = ScopeConfig_Scope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alibabacloud_v1beta1_scope_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScopeConfig_Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeConfig_Scope) ProtoMessage() {}

func (x *ScopeConfig_Scope) ProtoReflect() protoreflect.Message {
	mi := &file_alibabacloud_v1beta1_scope_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeConfig_Scope.ProtoReflect.Descriptor instead.
func (*ScopeConfig_Scope) Descriptor() ([]byte, []int) {
	return file_alibabacloud_v1beta1_scope_config_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ScopeConfig_Scope) GetSelector() *v1.LabelSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *ScopeConfig_Scope) GetRollingUpdate() *ScopeConfig_RollingUpdate {
	if x != nil {
		return x.RollingUpdate
	}
	return nil
}

var File_alibabacloud_v1beta1_scope_config_proto protoreflect.FileDescriptor

var file_alibabacloud_v1beta1_scope_config_proto_rawDesc = []byte{
	0x0a, 0x27, 0x61, 0x6c, 0x69, 0x62, 0x61, 0x62, 0x61, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x76,
	0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x69, 0x73, 0x74, 0x69, 0x6f,
	0x2e, 0x61, 0x6c, 0x69, 0x62, 0x61, 0x62, 0x61, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x76, 0x31,
	0x62, 0x65, 0x74, 0x61, 0x31, 0x1a, 0x34, 0x6b, 0x38, 0x73, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70,
	0x69, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x72, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61,
	0x70, 0x69, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x33, 0x6b, 0x38, 0x73,
	0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x72, 0x79,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x69, 0x6e, 0x74, 0x73, 0x74, 0x72,
	0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xd7, 0x02, 0x0a, 0x0b, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x43, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2d, 0x2e, 0x69, 0x73, 0x74, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x69, 0x62, 0x61, 0x62, 0x61, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x53, 0x63, 0x6f,
	0x70, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x52, 0x05,
	0x73, 0x63, 0x6f, 0x70, 0x65, 0x1a, 0x4b, 0x0a, 0x0d, 0x52, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x74, 0x63, 0x68, 0x4e,
	0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x62, 0x61, 0x74, 0x63, 0x68, 0x4e,
	0x75, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x62, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x1a, 0xb5, 0x01, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x4f, 0x0a, 0x08,
	0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33,
	0x2e, 0x6b, 0x38, 0x73, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x6d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x6d, 0x65,
	0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x5b, 0x0a,
	0x0d, 0x72, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x69, 0x73, 0x74, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x69,
	0x62, 0x61, 0x62, 0x61, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0x2e, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x6f,
	0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x0d, 0x72, 0x6f, 0x6c,
	0x6c, 0x69, 0x6e, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x23, 0x5a, 0x21, 0x69, 0x73,
	0x74, 0x69, 0x6f, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6c, 0x69, 0x62, 0x61,
	0x62, 0x61, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alibabacloud_v1beta1_scope_config_proto_rawDescOnce sync.Once
	file_alibabacloud_v1beta1_scope_config_proto_rawDescData = file_alibabacloud_v1beta1_scope_config_proto_rawDesc
)

func file_alibabacloud_v1beta1_scope_config_proto_rawDescGZIP() []byte {
	file_alibabacloud_v1beta1_scope_config_proto_rawDescOnce.Do(func() {
		file_alibabacloud_v1beta1_scope_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_alibabacloud_v1beta1_scope_config_proto_rawDescData)
	})
	return file_alibabacloud_v1beta1_scope_config_proto_rawDescData
}

var file_alibabacloud_v1beta1_scope_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_alibabacloud_v1beta1_scope_config_proto_goTypes = []interface{}{
	(*ScopeConfig)(nil),               // 0: istio.alibabacloud.v1beta1.ScopeConfig
	(*ScopeConfig_RollingUpdate)(nil), // 1: istio.alibabacloud.v1beta1.ScopeConfig.RollingUpdate
	(*ScopeConfig_Scope)(nil),         // 2: istio.alibabacloud.v1beta1.ScopeConfig.Scope
	(*v1.LabelSelector)(nil),          // 3: k8s.io.apimachinery.pkg.apis.meta.v1.LabelSelector
}
var file_alibabacloud_v1beta1_scope_config_proto_depIdxs = []int32{
	2, // 0: istio.alibabacloud.v1beta1.ScopeConfig.scope:type_name -> istio.alibabacloud.v1beta1.ScopeConfig.Scope
	3, // 1: istio.alibabacloud.v1beta1.ScopeConfig.Scope.selector:type_name -> k8s.io.apimachinery.pkg.apis.meta.v1.LabelSelector
	1, // 2: istio.alibabacloud.v1beta1.ScopeConfig.Scope.rollingUpdate:type_name -> istio.alibabacloud.v1beta1.ScopeConfig.RollingUpdate
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_alibabacloud_v1beta1_scope_config_proto_init() }
func file_alibabacloud_v1beta1_scope_config_proto_init() {
	if File_alibabacloud_v1beta1_scope_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alibabacloud_v1beta1_scope_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScopeConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alibabacloud_v1beta1_scope_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScopeConfig_RollingUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alibabacloud_v1beta1_scope_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScopeConfig_Scope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alibabacloud_v1beta1_scope_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alibabacloud_v1beta1_scope_config_proto_goTypes,
		DependencyIndexes: file_alibabacloud_v1beta1_scope_config_proto_depIdxs,
		MessageInfos:      file_alibabacloud_v1beta1_scope_config_proto_msgTypes,
	}.Build()
	File_alibabacloud_v1beta1_scope_config_proto = out.File
	file_alibabacloud_v1beta1_scope_config_proto_rawDesc = nil
	file_alibabacloud_v1beta1_scope_config_proto_goTypes = nil
	file_alibabacloud_v1beta1_scope_config_proto_depIdxs = nil
}
