// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1beta1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for ScopeConfig
func (this *ScopeConfig) MarshalJSON() ([]byte, error) {
	str, err := ScopeConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ScopeConfig
func (this *ScopeConfig) UnmarshalJSON(b []byte) error {
	return ScopeConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ScopeConfig_RollingUpdate
func (this *ScopeConfig_RollingUpdate) MarshalJSON() ([]byte, error) {
	str, err := ScopeConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ScopeConfig_RollingUpdate
func (this *ScopeConfig_RollingUpdate) UnmarshalJSON(b []byte) error {
	return ScopeConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ScopeConfig_Scope
func (this *ScopeConfig_Scope) MarshalJSON() ([]byte, error) {
	str, err := ScopeConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ScopeConfig_Scope
func (this *ScopeConfig_Scope) UnmarshalJSON(b []byte) error {
	return ScopeConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ScopeConfigMarshaler   = &jsonpb.Marshaler{}
	ScopeConfigUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
