// Copyright 2023 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: alibabacloud/v1beta1/traffic_label.proto

// In the Alibaba Cloud Service Mesh, traffic labeling refers to marking traffic for more detailed
// traffic control and management. By labeling traffic requests between application services
// with specific labels, they can be divided into different services or versions, and operations
// such as traffic control, circuit breaking, and rate limiting can be performed based on the labels.
//
// traffic labeling can be set for namespaces and workloads.
// `TrafficLabel` describes a way of traffic labeling. By defining specific traffic labeling custom resource,
// traffic labeling can be configured for specific workloads or by namespace.

package v1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1alpha3 "istio.io/api/networking/v1alpha3"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// `TrafficLabel` describes the configuration to apply the traffic label for specific workloads or by namespace.
//
// <!-- crd generation tags
// +cue-gen:TrafficLabel:groupName:istio.alibabacloud.com
// +cue-gen:TrafficLabel:version:v1beta1
// +cue-gen:TrafficLabel:storageVersion
// +cue-gen:TrafficLabel:annotations:helm.sh/resource-policy=keep
// +cue-gen:TrafficLabel:labels:app=istio-pilot,chart=istio,heritage=Tiller,release=istio
// +cue-gen:TrafficLabel:subresource:status
// +cue-gen:TrafficLabel:scope:Namespaced
// +cue-gen:TrafficLabel:resource:categories=alibabacloud-com,istio-alibabacloud-com,shortNames=tl
// +cue-gen:TrafficLabel:preserveUnknownFields:false
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=istio.alibabacloud.com/v1beta1
// +genclient
// +k8s:deepcopy-gen=true
// -->
type TrafficLabel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This refers to the scope of the workload to which the traffic labels will be applied.
	// The selector determines where the traffic label should be applied.
	// If not set, the selector will match all workloads in the current namespace.
	WorkloadSelector *v1alpha3.WorkloadSelector `protobuf:"bytes,1,opt,name=workload_selector,json=workloadSelector,proto3" json:"workload_selector,omitempty"`
	// The traffic rules for configuring the tags.
	Rules []*TrafficLabelRule `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	// The scope of the destination host which the traffic label rules should be applied.
	// "*" represents all services within the same namespace which the traffic label belongs to.
	// When short names are used (e.g. "reviews" instead of "reviews.default.svc.cluster.local"),
	// Istio will interpret the short name based on the namespace of the traffic label rule.
	// A rule in the "default" namespace containing a host "reviews" will be
	// interpreted as "reviews.default.svc.cluster.local". _To avoid
	// potential misconfigurations, it is recommended to always use fully
	// qualified domain names over short names._
	Hosts         []string `protobuf:"bytes,5,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficLabel) Reset() {
	*x = TrafficLabel{}
	mi := &file_alibabacloud_v1beta1_traffic_label_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficLabel) ProtoMessage() {}

func (x *TrafficLabel) ProtoReflect() protoreflect.Message {
	mi := &file_alibabacloud_v1beta1_traffic_label_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficLabel.ProtoReflect.Descriptor instead.
func (*TrafficLabel) Descriptor() ([]byte, []int) {
	return file_alibabacloud_v1beta1_traffic_label_proto_rawDescGZIP(), []int{0}
}

func (x *TrafficLabel) GetWorkloadSelector() *v1alpha3.WorkloadSelector {
	if x != nil {
		return x.WorkloadSelector
	}
	return nil
}

func (x *TrafficLabel) GetRules() []*TrafficLabelRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *TrafficLabel) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

// TrafficLabelRule describes the rule configuration of the traffic label.
type TrafficLabelRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The labels to be attached
	Labels []*LabelVar `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	// attach to all protocols
	AttachTo []string `protobuf:"bytes,3,rep,name=attachTo,proto3" json:"attachTo,omitempty"`
	// protocols on which this rule is applied
	// '*' stands for all protocols
	// ” stands for none
	Protocols string `protobuf:"bytes,4,opt,name=protocols,proto3" json:"protocols,omitempty"`
	// Configuration of specific rules for HTTP request
	Http          []*HTTPLabelRule `protobuf:"bytes,11,rep,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficLabelRule) Reset() {
	*x = TrafficLabelRule{}
	mi := &file_alibabacloud_v1beta1_traffic_label_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficLabelRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficLabelRule) ProtoMessage() {}

func (x *TrafficLabelRule) ProtoReflect() protoreflect.Message {
	mi := &file_alibabacloud_v1beta1_traffic_label_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficLabelRule.ProtoReflect.Descriptor instead.
func (*TrafficLabelRule) Descriptor() ([]byte, []int) {
	return file_alibabacloud_v1beta1_traffic_label_proto_rawDescGZIP(), []int{1}
}

func (x *TrafficLabelRule) GetLabels() []*LabelVar {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *TrafficLabelRule) GetAttachTo() []string {
	if x != nil {
		return x.AttachTo
	}
	return nil
}

func (x *TrafficLabelRule) GetProtocols() string {
	if x != nil {
		return x.Protocols
	}
	return ""
}

func (x *TrafficLabelRule) GetHttp() []*HTTPLabelRule {
	if x != nil {
		return x.Http
	}
	return nil
}

// LabelVar describes the properties of label, e.g. name and value.
type LabelVar struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of label
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The value of label. The parameter value of valueFrom follows a natural order of priority,
	// with the tag value first obtained from the first row and only obtained from the second row
	// when it is not available, and so on.
	ValueFrom []string `protobuf:"bytes,2,rep,name=valueFrom,proto3" json:"valueFrom,omitempty"`
	// Overwrite specifies whether the corresponding values of the original request header should be overwritten
	Overwrite     bool `protobuf:"varint,5,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelVar) Reset() {
	*x = LabelVar{}
	mi := &file_alibabacloud_v1beta1_traffic_label_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelVar) ProtoMessage() {}

func (x *LabelVar) ProtoReflect() protoreflect.Message {
	mi := &file_alibabacloud_v1beta1_traffic_label_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelVar.ProtoReflect.Descriptor instead.
func (*LabelVar) Descriptor() ([]byte, []int) {
	return file_alibabacloud_v1beta1_traffic_label_proto_rawDescGZIP(), []int{2}
}

func (x *LabelVar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LabelVar) GetValueFrom() []string {
	if x != nil {
		return x.ValueFrom
	}
	return nil
}

func (x *LabelVar) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

// HTTPLabelRule describes the rule configuration for http protocol
type HTTPLabelRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Match conditions to be satisfied for the rule to be
	// activated. All conditions inside a single match block have AND
	// semantics, while the list of match blocks have OR semantics. The rule
	// is matched if any one of the match blocks succeed.
	Match []*v1alpha3.HTTPMatchRequest `protobuf:"bytes,1,rep,name=match,proto3" json:"match,omitempty"`
	// labels for http request
	Labels []*LabelVar `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`
	// attach to http request
	AttachTo      []string `protobuf:"bytes,6,rep,name=attachTo,proto3" json:"attachTo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPLabelRule) Reset() {
	*x = HTTPLabelRule{}
	mi := &file_alibabacloud_v1beta1_traffic_label_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPLabelRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPLabelRule) ProtoMessage() {}

func (x *HTTPLabelRule) ProtoReflect() protoreflect.Message {
	mi := &file_alibabacloud_v1beta1_traffic_label_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPLabelRule.ProtoReflect.Descriptor instead.
func (*HTTPLabelRule) Descriptor() ([]byte, []int) {
	return file_alibabacloud_v1beta1_traffic_label_proto_rawDescGZIP(), []int{3}
}

func (x *HTTPLabelRule) GetMatch() []*v1alpha3.HTTPMatchRequest {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *HTTPLabelRule) GetLabels() []*LabelVar {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *HTTPLabelRule) GetAttachTo() []string {
	if x != nil {
		return x.AttachTo
	}
	return nil
}

var File_alibabacloud_v1beta1_traffic_label_proto protoreflect.FileDescriptor

const file_alibabacloud_v1beta1_traffic_label_proto_rawDesc = "" +
	"\n" +
	"(alibabacloud/v1beta1/traffic_label.proto\x12\x1aistio.alibabacloud.v1beta1\x1a!networking/v1alpha3/sidecar.proto\x1a)networking/v1alpha3/virtual_service.proto\"\xc2\x01\n" +
	"\fTrafficLabel\x12X\n" +
	"\x11workload_selector\x18\x01 \x01(\v2+.istio.networking.v1alpha3.WorkloadSelectorR\x10workloadSelector\x12B\n" +
	"\x05rules\x18\x02 \x03(\v2,.istio.alibabacloud.v1beta1.TrafficLabelRuleR\x05rules\x12\x14\n" +
	"\x05hosts\x18\x05 \x03(\tR\x05hosts\"\xc9\x01\n" +
	"\x10TrafficLabelRule\x12<\n" +
	"\x06labels\x18\x02 \x03(\v2$.istio.alibabacloud.v1beta1.LabelVarR\x06labels\x12\x1a\n" +
	"\battachTo\x18\x03 \x03(\tR\battachTo\x12\x1c\n" +
	"\tprotocols\x18\x04 \x01(\tR\tprotocols\x12=\n" +
	"\x04http\x18\v \x03(\v2).istio.alibabacloud.v1beta1.HTTPLabelRuleR\x04http\"Z\n" +
	"\bLabelVar\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tvalueFrom\x18\x02 \x03(\tR\tvalueFrom\x12\x1c\n" +
	"\toverwrite\x18\x05 \x01(\bR\toverwrite\"\xac\x01\n" +
	"\rHTTPLabelRule\x12A\n" +
	"\x05match\x18\x01 \x03(\v2+.istio.networking.v1alpha3.HTTPMatchRequestR\x05match\x12<\n" +
	"\x06labels\x18\x05 \x03(\v2$.istio.alibabacloud.v1beta1.LabelVarR\x06labels\x12\x1a\n" +
	"\battachTo\x18\x06 \x03(\tR\battachToB#Z!istio.io/api/alibabacloud/v1beta1b\x06proto3"

var (
	file_alibabacloud_v1beta1_traffic_label_proto_rawDescOnce sync.Once
	file_alibabacloud_v1beta1_traffic_label_proto_rawDescData []byte
)

func file_alibabacloud_v1beta1_traffic_label_proto_rawDescGZIP() []byte {
	file_alibabacloud_v1beta1_traffic_label_proto_rawDescOnce.Do(func() {
		file_alibabacloud_v1beta1_traffic_label_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alibabacloud_v1beta1_traffic_label_proto_rawDesc), len(file_alibabacloud_v1beta1_traffic_label_proto_rawDesc)))
	})
	return file_alibabacloud_v1beta1_traffic_label_proto_rawDescData
}

var file_alibabacloud_v1beta1_traffic_label_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_alibabacloud_v1beta1_traffic_label_proto_goTypes = []any{
	(*TrafficLabel)(nil),              // 0: istio.alibabacloud.v1beta1.TrafficLabel
	(*TrafficLabelRule)(nil),          // 1: istio.alibabacloud.v1beta1.TrafficLabelRule
	(*LabelVar)(nil),                  // 2: istio.alibabacloud.v1beta1.LabelVar
	(*HTTPLabelRule)(nil),             // 3: istio.alibabacloud.v1beta1.HTTPLabelRule
	(*v1alpha3.WorkloadSelector)(nil), // 4: istio.networking.v1alpha3.WorkloadSelector
	(*v1alpha3.HTTPMatchRequest)(nil), // 5: istio.networking.v1alpha3.HTTPMatchRequest
}
var file_alibabacloud_v1beta1_traffic_label_proto_depIdxs = []int32{
	4, // 0: istio.alibabacloud.v1beta1.TrafficLabel.workload_selector:type_name -> istio.networking.v1alpha3.WorkloadSelector
	1, // 1: istio.alibabacloud.v1beta1.TrafficLabel.rules:type_name -> istio.alibabacloud.v1beta1.TrafficLabelRule
	2, // 2: istio.alibabacloud.v1beta1.TrafficLabelRule.labels:type_name -> istio.alibabacloud.v1beta1.LabelVar
	3, // 3: istio.alibabacloud.v1beta1.TrafficLabelRule.http:type_name -> istio.alibabacloud.v1beta1.HTTPLabelRule
	5, // 4: istio.alibabacloud.v1beta1.HTTPLabelRule.match:type_name -> istio.networking.v1alpha3.HTTPMatchRequest
	2, // 5: istio.alibabacloud.v1beta1.HTTPLabelRule.labels:type_name -> istio.alibabacloud.v1beta1.LabelVar
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_alibabacloud_v1beta1_traffic_label_proto_init() }
func file_alibabacloud_v1beta1_traffic_label_proto_init() {
	if File_alibabacloud_v1beta1_traffic_label_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alibabacloud_v1beta1_traffic_label_proto_rawDesc), len(file_alibabacloud_v1beta1_traffic_label_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alibabacloud_v1beta1_traffic_label_proto_goTypes,
		DependencyIndexes: file_alibabacloud_v1beta1_traffic_label_proto_depIdxs,
		MessageInfos:      file_alibabacloud_v1beta1_traffic_label_proto_msgTypes,
	}.Build()
	File_alibabacloud_v1beta1_traffic_label_proto = out.File
	file_alibabacloud_v1beta1_traffic_label_proto_goTypes = nil
	file_alibabacloud_v1beta1_traffic_label_proto_depIdxs = nil
}
