//go:build !ignore_autogenerated

// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddressExtractor) DeepCopyInto(out *AddressExtractor) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddressExtractor.
func (in *AddressExtractor) DeepCopy() *AddressExtractor {
	if in == nil {
		return nil
	}
	out := new(AddressExtractor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AimdLoadScheduler) DeepCopyInto(out *AimdLoadScheduler) {
	*out = *in
	if in.Gradient != nil {
		in, out := &in.Gradient, &out.Gradient
		*out = new(GradientControllerParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadMultiplierLinearIncrement != nil {
		in, out := &in.LoadMultiplierLinearIncrement, &out.LoadMultiplierLinearIncrement
		*out = new(float64)
		**out = **in
	}
	if in.LoadScheduler != nil {
		in, out := &in.LoadScheduler, &out.LoadScheduler
		*out = new(LoadSchedulerParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxLoadMultiplier != nil {
		in, out := &in.MaxLoadMultiplier, &out.MaxLoadMultiplier
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AimdLoadScheduler.
func (in *AimdLoadScheduler) DeepCopy() *AimdLoadScheduler {
	if in == nil {
		return nil
	}
	out := new(AimdLoadScheduler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Alerter) DeepCopyInto(out *Alerter) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ResolveTimeout != nil {
		in, out := &in.ResolveTimeout, &out.ResolveTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Severity != nil {
		in, out := &in.Severity, &out.Severity
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Alerter.
func (in *Alerter) DeepCopy() *Alerter {
	if in == nil {
		return nil
	}
	out := new(Alerter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AndIns) DeepCopyInto(out *AndIns) {
	*out = *in
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]InPort, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AndIns.
func (in *AndIns) DeepCopy() *AndIns {
	if in == nil {
		return nil
	}
	out := new(AndIns)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AndOuts) DeepCopyInto(out *AndOuts) {
	*out = *in
	out.Output = in.Output
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AndOuts.
func (in *AndOuts) DeepCopy() *AndOuts {
	if in == nil {
		return nil
	}
	out := new(AndOuts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AverageLatencyDriver) DeepCopyInto(out *AverageLatencyDriver) {
	*out = *in
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = new([]Selector)
		if **in != nil {
			in, out := *in, *out
			*out = make([]Selector, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.MatchRequests != nil {
		in, out := &in.MatchRequests, &out.MatchRequests
		*out = make([]MatchRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Criteria != nil {
		in, out := &in.Criteria, &out.Criteria
		*out = new(DriverCriteria)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AverageLatencyDriver.
func (in *AverageLatencyDriver) DeepCopy() *AverageLatencyDriver {
	if in == nil {
		return nil
	}
	out := new(AverageLatencyDriver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AverageLatencySchedulingPolicy) DeepCopyInto(out *AverageLatencySchedulingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AverageLatencySchedulingPolicy.
func (in *AverageLatencySchedulingPolicy) DeepCopy() *AverageLatencySchedulingPolicy {
	if in == nil {
		return nil
	}
	out := new(AverageLatencySchedulingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AverageLatencySchedulingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AverageLatencySchedulingPolicyList) DeepCopyInto(out *AverageLatencySchedulingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AverageLatencySchedulingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AverageLatencySchedulingPolicyList.
func (in *AverageLatencySchedulingPolicyList) DeepCopy() *AverageLatencySchedulingPolicyList {
	if in == nil {
		return nil
	}
	out := new(AverageLatencySchedulingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AverageLatencySchedulingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AverageLatencySchedulingPolicySpec) DeepCopyInto(out *AverageLatencySchedulingPolicySpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(Resources)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadSchedulingCore != nil {
		in, out := &in.LoadSchedulingCore, &out.LoadSchedulingCore
		*out = new(LoadSchedulingCore)
		(*in).DeepCopyInto(*out)
	}
	if in.LatencyBaseliner != nil {
		in, out := &in.LatencyBaseliner, &out.LatencyBaseliner
		*out = new(LatencyBaseliner)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkloadSelector != nil {
		in, out := &in.WorkloadSelector, &out.WorkloadSelector
		*out = new(WorkloadSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplyToTraffic != nil {
		in, out := &in.ApplyToTraffic, &out.ApplyToTraffic
		*out = new(ApplyToTraffic)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AverageLatencySchedulingPolicySpec.
func (in *AverageLatencySchedulingPolicySpec) DeepCopy() *AverageLatencySchedulingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AverageLatencySchedulingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AverageLatencySchedulingPolicyStatus) DeepCopyInto(out *AverageLatencySchedulingPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AverageLatencySchedulingPolicyStatus.
func (in *AverageLatencySchedulingPolicyStatus) DeepCopy() *AverageLatencySchedulingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AverageLatencySchedulingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoolVariableComponent) DeepCopyInto(out *BoolVariableComponent) {
	*out = *in
	out.OutPorts = in.OutPorts
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoolVariableComponent.
func (in *BoolVariableComponent) DeepCopy() *BoolVariableComponent {
	if in == nil {
		return nil
	}
	out := new(BoolVariableComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoolVariableOuts) DeepCopyInto(out *BoolVariableOuts) {
	*out = *in
	out.Output = in.Output
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoolVariableOuts.
func (in *BoolVariableOuts) DeepCopy() *BoolVariableOuts {
	if in == nil {
		return nil
	}
	out := new(BoolVariableOuts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Classifier) DeepCopyInto(out *Classifier) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = new(map[string]Rule)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]Rule, len(*in))
			for key, val := range *in {
				(*out)[key] = *val.DeepCopy()
			}
		}
	}
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = new([]Selector)
		if **in != nil {
			in, out := *in, *out
			*out = make([]Selector, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Classifier.
func (in *Classifier) DeepCopy() *Classifier {
	if in == nil {
		return nil
	}
	out := new(Classifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Component) DeepCopyInto(out *Component) {
	*out = *in
	if in.Query != nil {
		in, out := &in.Query, &out.Query
		*out = new(Query)
		(*in).DeepCopyInto(*out)
	}
	if in.Decider != nil {
		in, out := &in.Decider, &out.Decider
		*out = new(Decider)
		(*in).DeepCopyInto(*out)
	}
	if in.BoolVariable != nil {
		in, out := &in.BoolVariable, &out.BoolVariable
		*out = new(BoolVariableComponent)
		**out = **in
	}
	if in.OrVariable != nil {
		in, out := &in.OrVariable, &out.OrVariable
		*out = new(LogicalORComponent)
		(*in).DeepCopyInto(*out)
	}
	if in.AndVariable != nil {
		in, out := &in.AndVariable, &out.AndVariable
		*out = new(LogicalAndComponent)
		(*in).DeepCopyInto(*out)
	}
	if in.FirstValid != nil {
		in, out := &in.FirstValid, &out.FirstValid
		*out = new(FirstValidComponent)
		(*in).DeepCopyInto(*out)
	}
	if in.Inverter != nil {
		in, out := &in.Inverter, &out.Inverter
		*out = new(LogicalInverterComponent)
		(*in).DeepCopyInto(*out)
	}
	if in.FlowControl != nil {
		in, out := &in.FlowControl, &out.FlowControl
		*out = new(FlowControlComponent)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Component.
func (in *Component) DeepCopy() *Component {
	if in == nil {
		return nil
	}
	out := new(Component)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConcurrencyLimiter) DeepCopyInto(out *ConcurrencyLimiter) {
	*out = *in
	if in.MaxConcurrency != nil {
		in, out := &in.MaxConcurrency, &out.MaxConcurrency
		*out = new(int64)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(ConcurrencyLimiterParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestParameters != nil {
		in, out := &in.RequestParameters, &out.RequestParameters
		*out = new(RateLimiterRequestParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Alerter != nil {
		in, out := &in.Alerter, &out.Alerter
		*out = new(Alerter)
		(*in).DeepCopyInto(*out)
	}
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = make([]Selector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MatchRequests != nil {
		in, out := &in.MatchRequests, &out.MatchRequests
		*out = make([]MatchRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrencyLimiter.
func (in *ConcurrencyLimiter) DeepCopy() *ConcurrencyLimiter {
	if in == nil {
		return nil
	}
	out := new(ConcurrencyLimiter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConcurrencyLimiterParameters) DeepCopyInto(out *ConcurrencyLimiterParameters) {
	*out = *in
	if in.LimitByLabelKey != nil {
		in, out := &in.LimitByLabelKey, &out.LimitByLabelKey
		*out = new(string)
		**out = **in
	}
	if in.MaxIdleTime != nil {
		in, out := &in.MaxIdleTime, &out.MaxIdleTime
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.MaxInflightDuration != nil {
		in, out := &in.MaxInflightDuration, &out.MaxInflightDuration
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrencyLimiterParameters.
func (in *ConcurrencyLimiterParameters) DeepCopy() *ConcurrencyLimiterParameters {
	if in == nil {
		return nil
	}
	out := new(ConcurrencyLimiterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConcurrencyLimitingPolicy) DeepCopyInto(out *ConcurrencyLimitingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrencyLimitingPolicy.
func (in *ConcurrencyLimitingPolicy) DeepCopy() *ConcurrencyLimitingPolicy {
	if in == nil {
		return nil
	}
	out := new(ConcurrencyLimitingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConcurrencyLimitingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConcurrencyLimitingPolicyList) DeepCopyInto(out *ConcurrencyLimitingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConcurrencyLimitingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrencyLimitingPolicyList.
func (in *ConcurrencyLimitingPolicyList) DeepCopy() *ConcurrencyLimitingPolicyList {
	if in == nil {
		return nil
	}
	out := new(ConcurrencyLimitingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConcurrencyLimitingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConcurrencyLimitingPolicySpec) DeepCopyInto(out *ConcurrencyLimitingPolicySpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(Resources)
		(*in).DeepCopyInto(*out)
	}
	if in.ConcurrencyLimiter != nil {
		in, out := &in.ConcurrencyLimiter, &out.ConcurrencyLimiter
		*out = new(ConcurrencyLimiter)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkloadSelector != nil {
		in, out := &in.WorkloadSelector, &out.WorkloadSelector
		*out = new(WorkloadSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplyToTraffic != nil {
		in, out := &in.ApplyToTraffic, &out.ApplyToTraffic
		*out = new(ApplyToTraffic)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrencyLimitingPolicySpec.
func (in *ConcurrencyLimitingPolicySpec) DeepCopy() *ConcurrencyLimitingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ConcurrencyLimitingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConcurrencyLimitingPolicyStatus) DeepCopyInto(out *ConcurrencyLimitingPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrencyLimitingPolicyStatus.
func (in *ConcurrencyLimitingPolicyStatus) DeepCopy() *ConcurrencyLimitingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ConcurrencyLimitingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConcurrencyScheduler) DeepCopyInto(out *ConcurrencyScheduler) {
	*out = *in
	if in.Alerter != nil {
		in, out := &in.Alerter, &out.Alerter
		*out = new(Alerter)
		(*in).DeepCopyInto(*out)
	}
	if in.ConcurrencyLimiter != nil {
		in, out := &in.ConcurrencyLimiter, &out.ConcurrencyLimiter
		*out = new(ConcurrencyLimiterParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxConcurrency != nil {
		in, out := &in.MaxConcurrency, &out.MaxConcurrency
		*out = new(int64)
		**out = **in
	}
	if in.Scheduler != nil {
		in, out := &in.Scheduler, &out.Scheduler
		*out = new(Scheduler)
		(*in).DeepCopyInto(*out)
	}
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = make([]Selector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MatchRequests != nil {
		in, out := &in.MatchRequests, &out.MatchRequests
		*out = make([]MatchRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrencyScheduler.
func (in *ConcurrencyScheduler) DeepCopy() *ConcurrencyScheduler {
	if in == nil {
		return nil
	}
	out := new(ConcurrencyScheduler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConcurrencySchedulingPolicy) DeepCopyInto(out *ConcurrencySchedulingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrencySchedulingPolicy.
func (in *ConcurrencySchedulingPolicy) DeepCopy() *ConcurrencySchedulingPolicy {
	if in == nil {
		return nil
	}
	out := new(ConcurrencySchedulingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConcurrencySchedulingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConcurrencySchedulingPolicyList) DeepCopyInto(out *ConcurrencySchedulingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConcurrencySchedulingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrencySchedulingPolicyList.
func (in *ConcurrencySchedulingPolicyList) DeepCopy() *ConcurrencySchedulingPolicyList {
	if in == nil {
		return nil
	}
	out := new(ConcurrencySchedulingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConcurrencySchedulingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConcurrencySchedulingPolicySpec) DeepCopyInto(out *ConcurrencySchedulingPolicySpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(Resources)
		(*in).DeepCopyInto(*out)
	}
	if in.ConcurrencyScheduler != nil {
		in, out := &in.ConcurrencyScheduler, &out.ConcurrencyScheduler
		*out = new(ConcurrencyScheduler)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkloadSelector != nil {
		in, out := &in.WorkloadSelector, &out.WorkloadSelector
		*out = new(WorkloadSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplyToTraffic != nil {
		in, out := &in.ApplyToTraffic, &out.ApplyToTraffic
		*out = new(ApplyToTraffic)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrencySchedulingPolicySpec.
func (in *ConcurrencySchedulingPolicySpec) DeepCopy() *ConcurrencySchedulingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ConcurrencySchedulingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConcurrencySchedulingPolicyStatus) DeepCopyInto(out *ConcurrencySchedulingPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrencySchedulingPolicyStatus.
func (in *ConcurrencySchedulingPolicyStatus) DeepCopy() *ConcurrencySchedulingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ConcurrencySchedulingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstantSignal) DeepCopyInto(out *ConstantSignal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstantSignal.
func (in *ConstantSignal) DeepCopy() *ConstantSignal {
	if in == nil {
		return nil
	}
	out := new(ConstantSignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Constants) DeepCopyInto(out *Constants) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Constants.
func (in *Constants) DeepCopy() *Constants {
	if in == nil {
		return nil
	}
	out := new(Constants)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Criteria) DeepCopyInto(out *Criteria) {
	*out = *in
	if in.Threshold != nil {
		in, out := &in.Threshold, &out.Threshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Criteria.
func (in *Criteria) DeepCopy() *Criteria {
	if in == nil {
		return nil
	}
	out := new(Criteria)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Decider) DeepCopyInto(out *Decider) {
	*out = *in
	if in.InPorts != nil {
		in, out := &in.InPorts, &out.InPorts
		*out = make(map[string]Port, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.OutPorts != nil {
		in, out := &in.OutPorts, &out.OutPorts
		*out = make(map[string]Port, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Decider.
func (in *Decider) DeepCopy() *Decider {
	if in == nil {
		return nil
	}
	out := new(Decider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Driver) DeepCopyInto(out *Driver) {
	*out = *in
	in.Criteria.DeepCopyInto(&out.Criteria)
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.FluxMeter.DeepCopyInto(&out.FluxMeter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Driver.
func (in *Driver) DeepCopy() *Driver {
	if in == nil {
		return nil
	}
	out := new(Driver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverAccumulator) DeepCopyInto(out *DriverAccumulator) {
	*out = *in
	if in.FluxMeters != nil {
		in, out := &in.FluxMeters, &out.FluxMeters
		*out = make(map[string]FluxMeter, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ForwardSignals != nil {
		in, out := &in.ForwardSignals, &out.ForwardSignals
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BackwardSignals != nil {
		in, out := &in.BackwardSignals, &out.BackwardSignals
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResetSignals != nil {
		in, out := &in.ResetSignals, &out.ResetSignals
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]Component, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverAccumulator.
func (in *DriverAccumulator) DeepCopy() *DriverAccumulator {
	if in == nil {
		return nil
	}
	out := new(DriverAccumulator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverCriteria) DeepCopyInto(out *DriverCriteria) {
	*out = *in
	if in.Backward != nil {
		in, out := &in.Backward, &out.Backward
		*out = new(Criteria)
		(*in).DeepCopyInto(*out)
	}
	if in.Forward != nil {
		in, out := &in.Forward, &out.Forward
		*out = new(Criteria)
		(*in).DeepCopyInto(*out)
	}
	if in.Reset != nil {
		in, out := &in.Reset, &out.Reset
		*out = new(Criteria)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverCriteria.
func (in *DriverCriteria) DeepCopy() *DriverCriteria {
	if in == nil {
		return nil
	}
	out := new(DriverCriteria)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Drivers) DeepCopyInto(out *Drivers) {
	*out = *in
	if in.AverageLatencyDrivers != nil {
		in, out := &in.AverageLatencyDrivers, &out.AverageLatencyDrivers
		*out = new([]AverageLatencyDriver)
		if **in != nil {
			in, out := *in, *out
			*out = make([]AverageLatencyDriver, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.PercentileLatencyDrivers != nil {
		in, out := &in.PercentileLatencyDrivers, &out.PercentileLatencyDrivers
		*out = new([]PercentileLatencyDriver)
		if **in != nil {
			in, out := *in, *out
			*out = make([]PercentileLatencyDriver, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.PromqlDrivers != nil {
		in, out := &in.PromqlDrivers, &out.PromqlDrivers
		*out = new([]PromqlDriver)
		if **in != nil {
			in, out := *in, *out
			*out = make([]PromqlDriver, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Drivers.
func (in *Drivers) DeepCopy() *Drivers {
	if in == nil {
		return nil
	}
	out := new(Drivers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EqualsExpression) DeepCopyInto(out *EqualsExpression) {
	*out = *in
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EqualsExpression.
func (in *EqualsExpression) DeepCopy() *EqualsExpression {
	if in == nil {
		return nil
	}
	out := new(EqualsExpression)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Expression) DeepCopyInto(out *Expression) {
	*out = *in
	if in.All != nil {
		in, out := &in.All, &out.All
		*out = new(ExpressionList)
		(*in).DeepCopyInto(*out)
	}
	if in.Any != nil {
		in, out := &in.Any, &out.Any
		*out = new(ExpressionList)
		(*in).DeepCopyInto(*out)
	}
	if in.LabelEquals != nil {
		in, out := &in.LabelEquals, &out.LabelEquals
		*out = new(EqualsExpression)
		(*in).DeepCopyInto(*out)
	}
	if in.LabelExists != nil {
		in, out := &in.LabelExists, &out.LabelExists
		*out = new(string)
		**out = **in
	}
	if in.LabelMatches != nil {
		in, out := &in.LabelMatches, &out.LabelMatches
		*out = new(MatchesExpression)
		(*in).DeepCopyInto(*out)
	}
	if in.Not != nil {
		in, out := &in.Not, &out.Not
		*out = new(NotExpression)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Expression.
func (in *Expression) DeepCopy() *Expression {
	if in == nil {
		return nil
	}
	out := new(Expression)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpressionList) DeepCopyInto(out *ExpressionList) {
	*out = *in
	if in.Of != nil {
		in, out := &in.Of, &out.Of
		*out = new([]Expression)
		if **in != nil {
			in, out := *in, *out
			*out = make([]Expression, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpressionList.
func (in *ExpressionList) DeepCopy() *ExpressionList {
	if in == nil {
		return nil
	}
	out := new(ExpressionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Extractor) DeepCopyInto(out *Extractor) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(AddressExtractor)
		(*in).DeepCopyInto(*out)
	}
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.Json != nil {
		in, out := &in.Json, &out.Json
		*out = new(JSONExtractor)
		(*in).DeepCopyInto(*out)
	}
	if in.JWT != nil {
		in, out := &in.JWT, &out.JWT
		*out = new(JWTExtractor)
		(*in).DeepCopyInto(*out)
	}
	if in.PathTemplates != nil {
		in, out := &in.PathTemplates, &out.PathTemplates
		*out = new(PathTemplateMatcher)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Extractor.
func (in *Extractor) DeepCopy() *Extractor {
	if in == nil {
		return nil
	}
	out := new(Extractor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirstValidComponent) DeepCopyInto(out *FirstValidComponent) {
	*out = *in
	in.InPorts.DeepCopyInto(&out.InPorts)
	out.OutPorts = in.OutPorts
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirstValidComponent.
func (in *FirstValidComponent) DeepCopy() *FirstValidComponent {
	if in == nil {
		return nil
	}
	out := new(FirstValidComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirstValidIns) DeepCopyInto(out *FirstValidIns) {
	*out = *in
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]InPort, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirstValidIns.
func (in *FirstValidIns) DeepCopy() *FirstValidIns {
	if in == nil {
		return nil
	}
	out := new(FirstValidIns)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirstValidOuts) DeepCopyInto(out *FirstValidOuts) {
	*out = *in
	out.Output = in.Output
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirstValidOuts.
func (in *FirstValidOuts) DeepCopy() *FirstValidOuts {
	if in == nil {
		return nil
	}
	out := new(FirstValidOuts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowControlComponent) DeepCopyInto(out *FlowControlComponent) {
	*out = *in
	if in.LoadRamp != nil {
		in, out := &in.LoadRamp, &out.LoadRamp
		*out = new(LoadRampComponent)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowControlComponent.
func (in *FlowControlComponent) DeepCopy() *FlowControlComponent {
	if in == nil {
		return nil
	}
	out := new(FlowControlComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowControlResources) DeepCopyInto(out *FlowControlResources) {
	*out = *in
	if in.Classifiers != nil {
		in, out := &in.Classifiers, &out.Classifiers
		*out = new([]Classifier)
		if **in != nil {
			in, out := *in, *out
			*out = make([]Classifier, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowControlResources.
func (in *FlowControlResources) DeepCopy() *FlowControlResources {
	if in == nil {
		return nil
	}
	out := new(FlowControlResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxMeter) DeepCopyInto(out *FluxMeter) {
	*out = *in
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = new([]Selector)
		if **in != nil {
			in, out := *in, *out
			*out = make([]Selector, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxMeter.
func (in *FluxMeter) DeepCopy() *FluxMeter {
	if in == nil {
		return nil
	}
	out := new(FluxMeter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxMeterExponentialBuckets) DeepCopyInto(out *FluxMeterExponentialBuckets) {
	*out = *in
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(int32)
		**out = **in
	}
	if in.Factor != nil {
		in, out := &in.Factor, &out.Factor
		*out = new(float64)
		**out = **in
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxMeterExponentialBuckets.
func (in *FluxMeterExponentialBuckets) DeepCopy() *FluxMeterExponentialBuckets {
	if in == nil {
		return nil
	}
	out := new(FluxMeterExponentialBuckets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxMeterExponentialBucketsRange) DeepCopyInto(out *FluxMeterExponentialBucketsRange) {
	*out = *in
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(int32)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(float64)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxMeterExponentialBucketsRange.
func (in *FluxMeterExponentialBucketsRange) DeepCopy() *FluxMeterExponentialBucketsRange {
	if in == nil {
		return nil
	}
	out := new(FluxMeterExponentialBucketsRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxMeterLinearBuckets) DeepCopyInto(out *FluxMeterLinearBuckets) {
	*out = *in
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(int32)
		**out = **in
	}
	if in.Width != nil {
		in, out := &in.Width, &out.Width
		*out = new(float64)
		**out = **in
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxMeterLinearBuckets.
func (in *FluxMeterLinearBuckets) DeepCopy() *FluxMeterLinearBuckets {
	if in == nil {
		return nil
	}
	out := new(FluxMeterLinearBuckets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxMeterStaticBuckets) DeepCopyInto(out *FluxMeterStaticBuckets) {
	*out = *in
	if in.Buckets != nil {
		in, out := &in.Buckets, &out.Buckets
		*out = new([]float64)
		if **in != nil {
			in, out := *in, *out
			*out = make([]float64, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxMeterStaticBuckets.
func (in *FluxMeterStaticBuckets) DeepCopy() *FluxMeterStaticBuckets {
	if in == nil {
		return nil
	}
	out := new(FluxMeterStaticBuckets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GradientControllerParameters) DeepCopyInto(out *GradientControllerParameters) {
	*out = *in
	if in.MaxGradient != nil {
		in, out := &in.MaxGradient, &out.MaxGradient
		*out = new(float64)
		**out = **in
	}
	if in.MinGradient != nil {
		in, out := &in.MinGradient, &out.MinGradient
		*out = new(float64)
		**out = **in
	}
	if in.Slope != nil {
		in, out := &in.Slope, &out.Slope
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GradientControllerParameters.
func (in *GradientControllerParameters) DeepCopy() *GradientControllerParameters {
	if in == nil {
		return nil
	}
	out := new(GradientControllerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InPort) DeepCopyInto(out *InPort) {
	*out = *in
	if in.ConstantSignal != nil {
		in, out := &in.ConstantSignal, &out.ConstantSignal
		*out = new(ConstantSignal)
		**out = **in
	}
	if in.SignalName != nil {
		in, out := &in.SignalName, &out.SignalName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InPort.
func (in *InPort) DeepCopy() *InPort {
	if in == nil {
		return nil
	}
	out := new(InPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ins) DeepCopyInto(out *Ins) {
	*out = *in
	out.Output = in.Output
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ins.
func (in *Ins) DeepCopy() *Ins {
	if in == nil {
		return nil
	}
	out := new(Ins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InverterIns) DeepCopyInto(out *InverterIns) {
	*out = *in
	in.Input.DeepCopyInto(&out.Input)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InverterIns.
func (in *InverterIns) DeepCopy() *InverterIns {
	if in == nil {
		return nil
	}
	out := new(InverterIns)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InverterOuts) DeepCopyInto(out *InverterOuts) {
	*out = *in
	out.Output = in.Output
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InverterOuts.
func (in *InverterOuts) DeepCopy() *InverterOuts {
	if in == nil {
		return nil
	}
	out := new(InverterOuts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JSONExtractor) DeepCopyInto(out *JSONExtractor) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.Pointer != nil {
		in, out := &in.Pointer, &out.Pointer
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JSONExtractor.
func (in *JSONExtractor) DeepCopy() *JSONExtractor {
	if in == nil {
		return nil
	}
	out := new(JSONExtractor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWTExtractor) DeepCopyInto(out *JWTExtractor) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.JsonPointer != nil {
		in, out := &in.JsonPointer, &out.JsonPointer
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWTExtractor.
func (in *JWTExtractor) DeepCopy() *JWTExtractor {
	if in == nil {
		return nil
	}
	out := new(JWTExtractor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelMatcher) DeepCopyInto(out *LabelMatcher) {
	*out = *in
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(Expression)
		(*in).DeepCopyInto(*out)
	}
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
	if in.MatchList != nil {
		in, out := &in.MatchList, &out.MatchList
		*out = new([]MatchRequirement)
		if **in != nil {
			in, out := *in, *out
			*out = make([]MatchRequirement, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelMatcher.
func (in *LabelMatcher) DeepCopy() *LabelMatcher {
	if in == nil {
		return nil
	}
	out := new(LabelMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LatencyBaseliner) DeepCopyInto(out *LatencyBaseliner) {
	*out = *in
	if in.LatencyToleranceMultiplier != nil {
		in, out := &in.LatencyToleranceMultiplier, &out.LatencyToleranceMultiplier
		*out = new(float64)
		**out = **in
	}
	if in.LongTermQueryInterval != nil {
		in, out := &in.LongTermQueryInterval, &out.LongTermQueryInterval
		*out = new(string)
		**out = **in
	}
	if in.LongTermQueryPeriodicInterval != nil {
		in, out := &in.LongTermQueryPeriodicInterval, &out.LongTermQueryPeriodicInterval
		*out = new(string)
		**out = **in
	}
	if in.Meter != nil {
		in, out := &in.Meter, &out.Meter
		*out = new(Meter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LatencyBaseliner.
func (in *LatencyBaseliner) DeepCopy() *LatencyBaseliner {
	if in == nil {
		return nil
	}
	out := new(LatencyBaseliner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadRamp) DeepCopyInto(out *LoadRamp) {
	*out = *in
	if in.Sampler != nil {
		in, out := &in.Sampler, &out.Sampler
		*out = new(Sampler)
		(*in).DeepCopyInto(*out)
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = new([]Step)
		if **in != nil {
			in, out := *in, *out
			*out = make([]Step, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadRamp.
func (in *LoadRamp) DeepCopy() *LoadRamp {
	if in == nil {
		return nil
	}
	out := new(LoadRamp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadRampComponent) DeepCopyInto(out *LoadRampComponent) {
	*out = *in
	if in.InPorts != nil {
		in, out := &in.InPorts, &out.InPorts
		*out = new(LoadRampIns)
		(*in).DeepCopyInto(*out)
	}
	if in.OutPorts != nil {
		in, out := &in.OutPorts, &out.OutPorts
		*out = new(LoadRampOuts)
		(*in).DeepCopyInto(*out)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(LoadRampParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.PassThroughLabelValues != nil {
		in, out := &in.PassThroughLabelValues, &out.PassThroughLabelValues
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadRampComponent.
func (in *LoadRampComponent) DeepCopy() *LoadRampComponent {
	if in == nil {
		return nil
	}
	out := new(LoadRampComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadRampIns) DeepCopyInto(out *LoadRampIns) {
	*out = *in
	if in.Backward != nil {
		in, out := &in.Backward, &out.Backward
		*out = new(InPort)
		(*in).DeepCopyInto(*out)
	}
	if in.Forward != nil {
		in, out := &in.Forward, &out.Forward
		*out = new(InPort)
		(*in).DeepCopyInto(*out)
	}
	if in.Reset != nil {
		in, out := &in.Reset, &out.Reset
		*out = new(InPort)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadRampIns.
func (in *LoadRampIns) DeepCopy() *LoadRampIns {
	if in == nil {
		return nil
	}
	out := new(LoadRampIns)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadRampOuts) DeepCopyInto(out *LoadRampOuts) {
	*out = *in
	if in.AcceptPercentage != nil {
		in, out := &in.AcceptPercentage, &out.AcceptPercentage
		*out = new(OutPort)
		**out = **in
	}
	if in.AtEnd != nil {
		in, out := &in.AtEnd, &out.AtEnd
		*out = new(OutPort)
		**out = **in
	}
	if in.AtStart != nil {
		in, out := &in.AtStart, &out.AtStart
		*out = new(OutPort)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadRampOuts.
func (in *LoadRampOuts) DeepCopy() *LoadRampOuts {
	if in == nil {
		return nil
	}
	out := new(LoadRampOuts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadRampParameters) DeepCopyInto(out *LoadRampParameters) {
	*out = *in
	if in.Sampler != nil {
		in, out := &in.Sampler, &out.Sampler
		*out = new(Sampler)
		(*in).DeepCopyInto(*out)
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = new([]Step)
		if **in != nil {
			in, out := *in, *out
			*out = make([]Step, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadRampParameters.
func (in *LoadRampParameters) DeepCopy() *LoadRampParameters {
	if in == nil {
		return nil
	}
	out := new(LoadRampParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadRampingPolicy) DeepCopyInto(out *LoadRampingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadRampingPolicy.
func (in *LoadRampingPolicy) DeepCopy() *LoadRampingPolicy {
	if in == nil {
		return nil
	}
	out := new(LoadRampingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadRampingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadRampingPolicyList) DeepCopyInto(out *LoadRampingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadRampingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadRampingPolicyList.
func (in *LoadRampingPolicyList) DeepCopy() *LoadRampingPolicyList {
	if in == nil {
		return nil
	}
	out := new(LoadRampingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadRampingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadRampingPolicySpec) DeepCopyInto(out *LoadRampingPolicySpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(Resources)
		(*in).DeepCopyInto(*out)
	}
	if in.Drivers != nil {
		in, out := &in.Drivers, &out.Drivers
		*out = new(Drivers)
		(*in).DeepCopyInto(*out)
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(bool)
		**out = **in
	}
	if in.Reset != nil {
		in, out := &in.Reset, &out.Reset
		*out = new(bool)
		**out = **in
	}
	if in.LoadRamp != nil {
		in, out := &in.LoadRamp, &out.LoadRamp
		*out = new(LoadRamp)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkloadSelector != nil {
		in, out := &in.WorkloadSelector, &out.WorkloadSelector
		*out = new(WorkloadSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplyToTraffic != nil {
		in, out := &in.ApplyToTraffic, &out.ApplyToTraffic
		*out = new(ApplyToTraffic)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadRampingPolicySpec.
func (in *LoadRampingPolicySpec) DeepCopy() *LoadRampingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(LoadRampingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadRampingPolicyStatus) DeepCopyInto(out *LoadRampingPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadRampingPolicyStatus.
func (in *LoadRampingPolicyStatus) DeepCopy() *LoadRampingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(LoadRampingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadSchedulerParameters) DeepCopyInto(out *LoadSchedulerParameters) {
	*out = *in
	if in.Scheduler != nil {
		in, out := &in.Scheduler, &out.Scheduler
		*out = new(Scheduler)
		(*in).DeepCopyInto(*out)
	}
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = new([]Selector)
		if **in != nil {
			in, out := *in, *out
			*out = make([]Selector, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.MatchRequests != nil {
		in, out := &in.MatchRequests, &out.MatchRequests
		*out = make([]MatchRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WorkloadLatencyBasedTokens != nil {
		in, out := &in.WorkloadLatencyBasedTokens, &out.WorkloadLatencyBasedTokens
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadSchedulerParameters.
func (in *LoadSchedulerParameters) DeepCopy() *LoadSchedulerParameters {
	if in == nil {
		return nil
	}
	out := new(LoadSchedulerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadSchedulingCore) DeepCopyInto(out *LoadSchedulingCore) {
	*out = *in
	if in.AimdLoadScheduler != nil {
		in, out := &in.AimdLoadScheduler, &out.AimdLoadScheduler
		*out = new(AimdLoadScheduler)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadSchedulingCore.
func (in *LoadSchedulingCore) DeepCopy() *LoadSchedulingCore {
	if in == nil {
		return nil
	}
	out := new(LoadSchedulingCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogicalAndComponent) DeepCopyInto(out *LogicalAndComponent) {
	*out = *in
	in.InPorts.DeepCopyInto(&out.InPorts)
	out.OutPorts = in.OutPorts
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogicalAndComponent.
func (in *LogicalAndComponent) DeepCopy() *LogicalAndComponent {
	if in == nil {
		return nil
	}
	out := new(LogicalAndComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogicalInverterComponent) DeepCopyInto(out *LogicalInverterComponent) {
	*out = *in
	in.InPorts.DeepCopyInto(&out.InPorts)
	out.OutPorts = in.OutPorts
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogicalInverterComponent.
func (in *LogicalInverterComponent) DeepCopy() *LogicalInverterComponent {
	if in == nil {
		return nil
	}
	out := new(LogicalInverterComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogicalORComponent) DeepCopyInto(out *LogicalORComponent) {
	*out = *in
	in.InPorts.DeepCopyInto(&out.InPorts)
	out.OutPorts = in.OutPorts
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogicalORComponent.
func (in *LogicalORComponent) DeepCopy() *LogicalORComponent {
	if in == nil {
		return nil
	}
	out := new(LogicalORComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchRequest) DeepCopyInto(out *MatchRequest) {
	*out = *in
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Scheme != nil {
		in, out := &in.Scheme, &out.Scheme
		*out = new(string)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TargetService != nil {
		in, out := &in.TargetService, &out.TargetService
		*out = new(TargetServiceRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchRequest.
func (in *MatchRequest) DeepCopy() *MatchRequest {
	if in == nil {
		return nil
	}
	out := new(MatchRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchRequirement) DeepCopyInto(out *MatchRequirement) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchRequirement.
func (in *MatchRequirement) DeepCopy() *MatchRequirement {
	if in == nil {
		return nil
	}
	out := new(MatchRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchesExpression) DeepCopyInto(out *MatchesExpression) {
	*out = *in
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.Regex != nil {
		in, out := &in.Regex, &out.Regex
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchesExpression.
func (in *MatchesExpression) DeepCopy() *MatchesExpression {
	if in == nil {
		return nil
	}
	out := new(MatchesExpression)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Meter) DeepCopyInto(out *Meter) {
	*out = *in
	if in.AttributeKey != nil {
		in, out := &in.AttributeKey, &out.AttributeKey
		*out = new(string)
		**out = **in
	}
	if in.ExponentialBuckets != nil {
		in, out := &in.ExponentialBuckets, &out.ExponentialBuckets
		*out = new(FluxMeterExponentialBuckets)
		(*in).DeepCopyInto(*out)
	}
	if in.ExponentialBucketsRange != nil {
		in, out := &in.ExponentialBucketsRange, &out.ExponentialBucketsRange
		*out = new(FluxMeterExponentialBucketsRange)
		(*in).DeepCopyInto(*out)
	}
	if in.LinearBuckets != nil {
		in, out := &in.LinearBuckets, &out.LinearBuckets
		*out = new(FluxMeterLinearBuckets)
		(*in).DeepCopyInto(*out)
	}
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = new([]Selector)
		if **in != nil {
			in, out := *in, *out
			*out = make([]Selector, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.MatchRequests != nil {
		in, out := &in.MatchRequests, &out.MatchRequests
		*out = make([]MatchRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StaticBuckets != nil {
		in, out := &in.StaticBuckets, &out.StaticBuckets
		*out = new(FluxMeterStaticBuckets)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Meter.
func (in *Meter) DeepCopy() *Meter {
	if in == nil {
		return nil
	}
	out := new(Meter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotExpression) DeepCopyInto(out *NotExpression) {
	*out = *in
	if in.All != nil {
		in, out := &in.All, &out.All
		*out = new(ExpressionList)
		(*in).DeepCopyInto(*out)
	}
	if in.Any != nil {
		in, out := &in.Any, &out.Any
		*out = new(ExpressionList)
		(*in).DeepCopyInto(*out)
	}
	if in.LabelEquals != nil {
		in, out := &in.LabelEquals, &out.LabelEquals
		*out = new(EqualsExpression)
		(*in).DeepCopyInto(*out)
	}
	if in.LabelExists != nil {
		in, out := &in.LabelExists, &out.LabelExists
		*out = new(string)
		**out = **in
	}
	if in.LabelMatches != nil {
		in, out := &in.LabelMatches, &out.LabelMatches
		*out = new(MatchesExpression)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotExpression.
func (in *NotExpression) DeepCopy() *NotExpression {
	if in == nil {
		return nil
	}
	out := new(NotExpression)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrIns) DeepCopyInto(out *OrIns) {
	*out = *in
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]InPort, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrIns.
func (in *OrIns) DeepCopy() *OrIns {
	if in == nil {
		return nil
	}
	out := new(OrIns)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrOuts) DeepCopyInto(out *OrOuts) {
	*out = *in
	out.Output = in.Output
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrOuts.
func (in *OrOuts) DeepCopy() *OrOuts {
	if in == nil {
		return nil
	}
	out := new(OrOuts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutPort) DeepCopyInto(out *OutPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutPort.
func (in *OutPort) DeepCopy() *OutPort {
	if in == nil {
		return nil
	}
	out := new(OutPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathTemplateMatcher) DeepCopyInto(out *PathTemplateMatcher) {
	*out = *in
	if in.TemplateValues != nil {
		in, out := &in.TemplateValues, &out.TemplateValues
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathTemplateMatcher.
func (in *PathTemplateMatcher) DeepCopy() *PathTemplateMatcher {
	if in == nil {
		return nil
	}
	out := new(PathTemplateMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PercentileLatencyDriver) DeepCopyInto(out *PercentileLatencyDriver) {
	*out = *in
	if in.Criteria != nil {
		in, out := &in.Criteria, &out.Criteria
		*out = new(DriverCriteria)
		(*in).DeepCopyInto(*out)
	}
	if in.FluxMeter != nil {
		in, out := &in.FluxMeter, &out.FluxMeter
		*out = new(Meter)
		(*in).DeepCopyInto(*out)
	}
	if in.Percentile != nil {
		in, out := &in.Percentile, &out.Percentile
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PercentileLatencyDriver.
func (in *PercentileLatencyDriver) DeepCopy() *PercentileLatencyDriver {
	if in == nil {
		return nil
	}
	out := new(PercentileLatencyDriver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Policy) DeepCopyInto(out *Policy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.DynamicConfig.DeepCopyInto(&out.DynamicConfig)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Policy.
func (in *Policy) DeepCopy() *Policy {
	if in == nil {
		return nil
	}
	out := new(Policy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Policy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyList) DeepCopyInto(out *PolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Policy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyList.
func (in *PolicyList) DeepCopy() *PolicyList {
	if in == nil {
		return nil
	}
	out := new(PolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatus) DeepCopyInto(out *PolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatus.
func (in *PolicyStatus) DeepCopy() *PolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Port) DeepCopyInto(out *Port) {
	*out = *in
	if in.SignalName != nil {
		in, out := &in.SignalName, &out.SignalName
		*out = new(string)
		**out = **in
	}
	if in.ConstantSignal != nil {
		in, out := &in.ConstantSignal, &out.ConstantSignal
		*out = new(ConstantSignal)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Port.
func (in *Port) DeepCopy() *Port {
	if in == nil {
		return nil
	}
	out := new(Port)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromQL) DeepCopyInto(out *PromQL) {
	*out = *in
	if in.OutPorts != nil {
		in, out := &in.OutPorts, &out.OutPorts
		*out = make(map[string]Port, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromQL.
func (in *PromQL) DeepCopy() *PromQL {
	if in == nil {
		return nil
	}
	out := new(PromQL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromqlDriver) DeepCopyInto(out *PromqlDriver) {
	*out = *in
	if in.Criteria != nil {
		in, out := &in.Criteria, &out.Criteria
		*out = new(DriverCriteria)
		(*in).DeepCopyInto(*out)
	}
	if in.QueryString != nil {
		in, out := &in.QueryString, &out.QueryString
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromqlDriver.
func (in *PromqlDriver) DeepCopy() *PromqlDriver {
	if in == nil {
		return nil
	}
	out := new(PromqlDriver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Query) DeepCopyInto(out *Query) {
	*out = *in
	in.Promql.DeepCopyInto(&out.Promql)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Query.
func (in *Query) DeepCopy() *Query {
	if in == nil {
		return nil
	}
	out := new(Query)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimiter) DeepCopyInto(out *RateLimiter) {
	*out = *in
	if in.Alerter != nil {
		in, out := &in.Alerter, &out.Alerter
		*out = new(Alerter)
		(*in).DeepCopyInto(*out)
	}
	if in.BucketCapacity != nil {
		in, out := &in.BucketCapacity, &out.BucketCapacity
		*out = new(float64)
		**out = **in
	}
	if in.FillAmount != nil {
		in, out := &in.FillAmount, &out.FillAmount
		*out = new(float64)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(RateLimiterParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestParameters != nil {
		in, out := &in.RequestParameters, &out.RequestParameters
		*out = new(RateLimiterRequestParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = make([]Selector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MatchRequests != nil {
		in, out := &in.MatchRequests, &out.MatchRequests
		*out = make([]MatchRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimiter.
func (in *RateLimiter) DeepCopy() *RateLimiter {
	if in == nil {
		return nil
	}
	out := new(RateLimiter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimiterParameters) DeepCopyInto(out *RateLimiterParameters) {
	*out = *in
	if in.ContinuousFill != nil {
		in, out := &in.ContinuousFill, &out.ContinuousFill
		*out = new(bool)
		**out = **in
	}
	if in.DelayInitialFill != nil {
		in, out := &in.DelayInitialFill, &out.DelayInitialFill
		*out = new(bool)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.LazySync != nil {
		in, out := &in.LazySync, &out.LazySync
		*out = new(RateLimiterParametersLazySync)
		(*in).DeepCopyInto(*out)
	}
	if in.LimitByLabelKey != nil {
		in, out := &in.LimitByLabelKey, &out.LimitByLabelKey
		*out = new(string)
		**out = **in
	}
	if in.MaxIdleTime != nil {
		in, out := &in.MaxIdleTime, &out.MaxIdleTime
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimiterParameters.
func (in *RateLimiterParameters) DeepCopy() *RateLimiterParameters {
	if in == nil {
		return nil
	}
	out := new(RateLimiterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimiterParametersLazySync) DeepCopyInto(out *RateLimiterParametersLazySync) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.NumSync != nil {
		in, out := &in.NumSync, &out.NumSync
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimiterParametersLazySync.
func (in *RateLimiterParametersLazySync) DeepCopy() *RateLimiterParametersLazySync {
	if in == nil {
		return nil
	}
	out := new(RateLimiterParametersLazySync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimiterRequestParameters) DeepCopyInto(out *RateLimiterRequestParameters) {
	*out = *in
	if in.DeniedResponseStatusCode != nil {
		in, out := &in.DeniedResponseStatusCode, &out.DeniedResponseStatusCode
		*out = new(int)
		**out = **in
	}
	if in.TokensLabelKey != nil {
		in, out := &in.TokensLabelKey, &out.TokensLabelKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimiterRequestParameters.
func (in *RateLimiterRequestParameters) DeepCopy() *RateLimiterRequestParameters {
	if in == nil {
		return nil
	}
	out := new(RateLimiterRequestParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitingPolicy) DeepCopyInto(out *RateLimitingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitingPolicy.
func (in *RateLimitingPolicy) DeepCopy() *RateLimitingPolicy {
	if in == nil {
		return nil
	}
	out := new(RateLimitingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RateLimitingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitingPolicyList) DeepCopyInto(out *RateLimitingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RateLimitingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitingPolicyList.
func (in *RateLimitingPolicyList) DeepCopy() *RateLimitingPolicyList {
	if in == nil {
		return nil
	}
	out := new(RateLimitingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RateLimitingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitingPolicySpec) DeepCopyInto(out *RateLimitingPolicySpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(Resources)
		(*in).DeepCopyInto(*out)
	}
	if in.RateLimiter != nil {
		in, out := &in.RateLimiter, &out.RateLimiter
		*out = new(RateLimiter)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkloadSelector != nil {
		in, out := &in.WorkloadSelector, &out.WorkloadSelector
		*out = new(WorkloadSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplyToTraffic != nil {
		in, out := &in.ApplyToTraffic, &out.ApplyToTraffic
		*out = new(ApplyToTraffic)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitingPolicySpec.
func (in *RateLimitingPolicySpec) DeepCopy() *RateLimitingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RateLimitingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitingPolicyStatus) DeepCopyInto(out *RateLimitingPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitingPolicyStatus.
func (in *RateLimitingPolicyStatus) DeepCopy() *RateLimitingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RateLimitingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resources) DeepCopyInto(out *Resources) {
	*out = *in
	if in.FlowControl != nil {
		in, out := &in.FlowControl, &out.FlowControl
		*out = new(FlowControlResources)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resources.
func (in *Resources) DeepCopy() *Resources {
	if in == nil {
		return nil
	}
	out := new(Resources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rule) DeepCopyInto(out *Rule) {
	*out = *in
	if in.Extractor != nil {
		in, out := &in.Extractor, &out.Extractor
		*out = new(Extractor)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rule.
func (in *Rule) DeepCopy() *Rule {
	if in == nil {
		return nil
	}
	out := new(Rule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Sampler) DeepCopyInto(out *Sampler) {
	*out = *in
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = new([]Selector)
		if **in != nil {
			in, out := *in, *out
			*out = make([]Selector, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.MatchRequests != nil {
		in, out := &in.MatchRequests, &out.MatchRequests
		*out = make([]MatchRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SessionLabelKey != nil {
		in, out := &in.SessionLabelKey, &out.SessionLabelKey
		*out = new(string)
		**out = **in
	}
	if in.DeniedResponseStatusCode != nil {
		in, out := &in.DeniedResponseStatusCode, &out.DeniedResponseStatusCode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Sampler.
func (in *Sampler) DeepCopy() *Sampler {
	if in == nil {
		return nil
	}
	out := new(Sampler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Scheduler) DeepCopyInto(out *Scheduler) {
	*out = *in
	if in.DecisionDeadlineMargin != nil {
		in, out := &in.DecisionDeadlineMargin, &out.DecisionDeadlineMargin
		*out = new(string)
		**out = **in
	}
	if in.DefaultWorkloadParameters != nil {
		in, out := &in.DefaultWorkloadParameters, &out.DefaultWorkloadParameters
		*out = new(SchedulerWorkloadParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.DeniedResponseStatusCode != nil {
		in, out := &in.DeniedResponseStatusCode, &out.DeniedResponseStatusCode
		*out = new(string)
		**out = **in
	}
	if in.FairnessLabelKey != nil {
		in, out := &in.FairnessLabelKey, &out.FairnessLabelKey
		*out = new(string)
		**out = **in
	}
	if in.PriorityLabelKey != nil {
		in, out := &in.PriorityLabelKey, &out.PriorityLabelKey
		*out = new(string)
		**out = **in
	}
	if in.TokensLabelKey != nil {
		in, out := &in.TokensLabelKey, &out.TokensLabelKey
		*out = new(string)
		**out = **in
	}
	if in.WorkloadLabelKey != nil {
		in, out := &in.WorkloadLabelKey, &out.WorkloadLabelKey
		*out = new(string)
		**out = **in
	}
	if in.Workloads != nil {
		in, out := &in.Workloads, &out.Workloads
		*out = new([]SchedulerWorkload)
		if **in != nil {
			in, out := *in, *out
			*out = make([]SchedulerWorkload, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Scheduler.
func (in *Scheduler) DeepCopy() *Scheduler {
	if in == nil {
		return nil
	}
	out := new(Scheduler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulerWorkload) DeepCopyInto(out *SchedulerWorkload) {
	*out = *in
	if in.LabelMatcher != nil {
		in, out := &in.LabelMatcher, &out.LabelMatcher
		*out = new(LabelMatcher)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(SchedulerWorkloadParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulerWorkload.
func (in *SchedulerWorkload) DeepCopy() *SchedulerWorkload {
	if in == nil {
		return nil
	}
	out := new(SchedulerWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulerWorkloadParameters) DeepCopyInto(out *SchedulerWorkloadParameters) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(float64)
		**out = **in
	}
	if in.QueueTimeout != nil {
		in, out := &in.QueueTimeout, &out.QueueTimeout
		*out = new(string)
		**out = **in
	}
	if in.Tokens != nil {
		in, out := &in.Tokens, &out.Tokens
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulerWorkloadParameters.
func (in *SchedulerWorkloadParameters) DeepCopy() *SchedulerWorkloadParameters {
	if in == nil {
		return nil
	}
	out := new(SchedulerWorkloadParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Selector) DeepCopyInto(out *Selector) {
	*out = *in
	if in.AgentGroup != nil {
		in, out := &in.AgentGroup, &out.AgentGroup
		*out = new(string)
		**out = **in
	}
	if in.ControlPoint != nil {
		in, out := &in.ControlPoint, &out.ControlPoint
		*out = new(string)
		**out = **in
	}
	if in.LabelMatcher != nil {
		in, out := &in.LabelMatcher, &out.LabelMatcher
		*out = new(LabelMatcher)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Selector.
func (in *Selector) DeepCopy() *Selector {
	if in == nil {
		return nil
	}
	out := new(Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusCode) DeepCopyInto(out *StatusCode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusCode.
func (in *StatusCode) DeepCopy() *StatusCode {
	if in == nil {
		return nil
	}
	out := new(StatusCode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Step) DeepCopyInto(out *Step) {
	*out = *in
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(string)
		**out = **in
	}
	if in.TargetAcceptPercentage != nil {
		in, out := &in.TargetAcceptPercentage, &out.TargetAcceptPercentage
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Step.
func (in *Step) DeepCopy() *Step {
	if in == nil {
		return nil
	}
	out := new(Step)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetServiceRef) DeepCopyInto(out *TargetServiceRef) {
	*out = *in
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(Group)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(Kind)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(PortNumber)
		**out = **in
	}
	if in.SectionName != nil {
		in, out := &in.SectionName, &out.SectionName
		*out = new(SectionName)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetServiceRef.
func (in *TargetServiceRef) DeepCopy() *TargetServiceRef {
	if in == nil {
		return nil
	}
	out := new(TargetServiceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSelector) DeepCopyInto(out *WorkloadSelector) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSelector.
func (in *WorkloadSelector) DeepCopy() *WorkloadSelector {
	if in == nil {
		return nil
	}
	out := new(WorkloadSelector)
	in.DeepCopyInto(out)
	return out
}
